### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by dmrickey** [cswendrowski/FoundryVTT-Drag-Upload#45]
```
foundry.js:2143 Uncaught (in promise) Error: This is not a registered game setting
[Detected 1 package: dragupload]
    at ClientSettings.get (foundry.js:2143:42)
    at createFoldersIfMissing (dragupload.js:71:42)
    at initializeDragUpload (dragupload.js:58:15)
    at dragupload.js:45:11
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at Game.setupGame (foundry.js:5547:11)
    at async Game._initializeGameView (foundry.js:6479:5)
    at async Game.initialize (foundry.js:5415:5)
```
Drag Upload v2.1.0
Foundy v9 242
system pf1 0.80.7

**Comment by Roger92** [comment]
Same here :)
