### ISSUE TITLE
10.285, PF2, Drag Upload prevents dragging monsters from sidebar to canvas

### ISSUE THREAD

**Issue by apoapostolov** [cswendrowski/FoundryVTT-Drag-Upload#58]
Error generated on attempt:

dragupload.js:144 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'callbacks')
[Detected 1 package: dragupload]
    at handleDrop (dragupload.js:144:30)
    at DragDrop.callback (foundry.js:56178:42)
    at DragDrop._handleDrop (foundry.js:56229:17)

**Comment by GregCMills** [comment]
This is the same problem as issue #57.

Doing this: https://github.com/cswendrowski/FoundryVTT-Drag-Upload/issues/57#issuecomment-1254402061 fixes it.
